services:
  - type: web
    name: compliance-backend
    runtime: docker
    plan: free
    region: oregon
    branch: develop
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT

  - type: web
    name: compliance-frontend
    runtime: docker
    plan: free
    region: oregon
    branch: develop
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: frontend
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        value: ""            # deja vacío si no conoces la URL; luego ponla en dashboard y redeploy
      - key: VITE_SUPABASE_URL
        value: "https://zyzmaaeoutsfstapbgmc.supabase.co"
      - key: VITE_SUPABASE_ANON_KEY
        value: "sb_publishable_LMCPeGJlx-MyhjKVHq1New_9"

databases: []