// Lista simple de países (código ISO2, nombre en español).
// Añade o sustituye entradas según necesites. Para producción puedes pegar la lista ISO completa.
const COUNTRIES = [
    { id: 'AF', name: 'Afganistán' },
    { id: 'AL', name: 'Albania' },
    { id: 'DZ', name: 'Argelia' },
    { id: 'AR', name: 'Argentina' },
    { id: 'AM', name: 'Armenia' },
    { id: 'AU', name: 'Australia' },
    { id: 'AT', name: 'Austria' },
    { id: 'AZ', name: 'Azerbaiyán' },
    { id: 'BS', name: 'Bahamas' },
    { id: 'BD', name: 'Bangladés' },
    { id: 'BB', name: 'Barbados' },
    { id: 'BE', name: 'Bélgica' },
    { id: 'BZ', name: 'Belice' },
    { id: 'BO', name: 'Bolivia' },
    { id: 'BR', name: 'Brasil' },
    { id: 'BG', name: 'Bulgaria' },
    { id: 'CA', name: 'Canadá' },
    { id: 'CL', name: 'Chile' },
    { id: 'CN', name: 'China' },
    { id: 'CO', name: 'Colombia' },
    { id: 'CR', name: 'Costa Rica' },
    { id: 'HR', name: 'Croacia' },
    { id: 'CU', name: 'Cuba' },
    { id: 'CY', name: 'Chipre' },
    { id: 'CZ', name: 'República Checa' },
    { id: 'DK', name: 'Dinamarca' },
    { id: 'DO', name: 'República Dominicana' },
    { id: 'EC', name: 'Ecuador' },
    { id: 'SV', name: 'El Salvador' },
    { id: 'EE', name: 'Estonia' },
    { id: 'FI', name: 'Finlandia' },
    { id: 'FR', name: 'Francia' },
    { id: 'DE', name: 'Alemania' },
    { id: 'GR', name: 'Grecia' },
    { id: 'GT', name: 'Guatemala' },
    { id: 'HN', name: 'Honduras' },
    { id: 'HU', name: 'Hungría' },
    { id: 'IS', name: 'Islandia' },
    { id: 'IN', name: 'India' },
    { id: 'ID', name: 'Indonesia' },
    { id: 'IE', name: 'Irlanda' },
    { id: 'IL', name: 'Israel' },
    { id: 'IT', name: 'Italia' },
    { id: 'JP', name: 'Japón' },
    { id: 'MX', name: 'México' },
    { id: 'NL', name: 'Países Bajos' },
    { id: 'NZ', name: 'Nueva Zelanda' },
    { id: 'NO', name: 'Noruega' },
    { id: 'PA', name: 'Panamá' },
    { id: 'PE', name: 'Perú' },
    { id: 'PH', name: 'Filipinas' },
    { id: 'PL', name: 'Polonia' },
    { id: 'PT', name: 'Portugal' },
    { id: 'RO', name: 'Rumanía' },
    { id: 'RU', name: 'Rusia' },
    { id: 'KN', name: 'San Cristóbal y Nieves' },
    { id: 'SA', name: 'Arabia Saudita' },
    { id: 'RS', name: 'Serbia' },
    { id: 'SG', name: 'Singapur' },
    { id: 'SK', name: 'Eslovaquia' },
    { id: 'SI', name: 'Eslovenia' },
    { id: 'ZA', name: 'Sudáfrica' },
    { id: 'KR', name: 'Corea del Sur' },
    { id: 'ES', name: 'España' },
    { id: 'SE', name: 'Suecia' },
    { id: 'CH', name: 'Suiza' },
    { id: 'TR', name: 'Turquía' },
    { id: 'UA', name: 'Ucrania' },
    { id: 'GB', name: 'Reino Unido' },
    { id: 'US', name: 'Estados Unidos' },
    { id: 'UY', name: 'Uruguay' },
    // ...añade más si los necesitas...
];

export default COUNTRIES;